### ISSUE TITLE
fuzzyhighlight: Invalid UTF-8 passed to drw_text

### ISSUE THREAD

**Issue by speedie1337** [bakkeby/dmenu-flexipatch#24]
If the fuzzy highlight patch is used along with Pango (maybe an issue with Xft too?) and emojis or non-English characters are highlighted, invalid UTF-8 is passed to the drw_text function. Looking at the function though I'm pretty sure this is because it doesn't properly handle Unicode made up of multiple characters when drawing each character. Not only does this result in the text not drawing properly, Pango will output many warnings about it.

I don't really have the time to fix this (and I'm really not familiar with encoding) but I thought I'd report the issue anyway.

**Comment by N-R-K** [comment]
Can you give some concrete examples, and maybe screenshots?

**Comment by speedie1337** [comment]
1. Enable Pango, fuzzy matching and fuzzy highligting
2. printf "%s\n" "åäö" | dmenu
3. Call some function that redraws the menu (e.g. press tab)

You get similar results with any non-ASCII characters. I think the problem from glancing over the fuzzy matching code is we're not necessarily iterating over each *UTF-8* character, so perhaps an incomplete (and thus invalid) character is passed to drw_text().

![image](https://github.com/bakkeby/dmenu-flexipatch/assets/71722170/ed57d1ba-c317-424b-8bef-776b73d24155)

**Comment by N-R-K** [comment]
I was actually looking into this but then it went off my mind. Basically the way dmenu (or libsl rather) deals with invalid utf8 doesn't make much sense.

It does it's calculation on an imaginary U+FFFD but then hands off the invalid utf8 to xft. Which on my system just cuts the text off at the first invalid byte.

```console
$ printf "0\xef1234567\ntest" | dmenu
````

![pic0](https://github.com/bakkeby/dmenu-flexipatch/assets/79544946/0e51d2ac-2f41-49b4-a2a2-5a0736aa9c40)

It'd probably be better if it actually rendered invalid sequence as U+FFFD instead of using it only for width calculations.

![pic1](https://github.com/bakkeby/dmenu-flexipatch/assets/79544946/e81bd6c1-eac3-47d3-bef8-dcb38dd1ba26)

I've sent a mail to the dev mailing list about this: https://lists.suckless.org/dev/2407/35646.html. I'll try to fix it upstream depending on what the expected behavior is.

**Comment by bakkeby** [comment]
I had a look at this and the particular issue that speedie reports here is isolated to the fuzzyhighlight patch.

The underlying issue is that the patch assumes that each letter takes up one char / byte and thus sends broken multi-byte characters to `drw_text`.

I played around with an example using libgrapheme to get the correct length for multi-byte UTF-8 characters and got fuzzy highlights working.

![image](https://github.com/bakkeby/dmenu-flexipatch/assets/1438008/27426727-ebb6-4787-8945-69867f71865d)

```diff
diff --git a/patch/fuzzyhighlight.c b/patch/fuzzyhighlight.c
index d31a150..5b90c2d 100644
--- a/patch/fuzzyhighlight.c
+++ b/patch/fuzzyhighlight.c
@@ -6,6 +6,7 @@ drawhighlights(struct item *item, int x, int y, int maxw)
 #endif // EMOJI_HIGHLIGHT_PATCH
 {
        int i, indent;
+       int utf8charlen;
        char *highlight;
        char c;

@@ -33,8 +34,9 @@ drawhighlights(struct item *item, int x, int y, int maxw)
                           ? SchemeSelHighlight
                           : SchemeNormHighlight]);
        for (i = 0, highlight = itemtext; *highlight && text[i];) {
+               utf8charlen = grapheme_next_character_break_utf8(highlight, SIZE_MAX);
                #if FUZZYMATCH_PATCH
-               if (!fstrncmp(&(*highlight), &text[i], 1))
+               if (!fstrncmp(&(*highlight), &text[i], utf8charlen))
                #else
                if (*highlight == text[i])
                #endif // FUZZYMATCH_PATCH
@@ -46,8 +48,8 @@ drawhighlights(struct item *item, int x, int y, int maxw)
                        *highlight = c;

                        /* highlight character */
-                       c = highlight[1];
-                       highlight[1] = '\0';
+                       c = highlight[utf8charlen];
+                       highlight[utf8charlen] = '\0';
                        drw_text(
                                drw,
                                x + indent + (lrpad / 2),
@@ -58,8 +60,8 @@ drawhighlights(struct item *item, int x, int y, int maxw)
                                , True
                                #endif // PANGO_PATCH
                        );
-                       highlight[1] = c;
-                       i++;
+                       highlight[utf8charlen] = c;
+                       i += utf8charlen;
                }
                highlight++;
        }
```

As for the invalid UTF-8 issue that would be unrelated to the Pango patch, but using libgrapheme one could sanity check that the character is valid UTF-8 and bail if not, e.g.

```c
			utf8charlen = grapheme_next_character_break_utf8(text, SIZE_MAX);
			if (!grapheme_decode_utf8(text, utf8charlen, &utf8codepoint)) {
				/* Bail in the event the string ended unexpectedly in the middle of a multi-byte
				 * sequence. */
				overflow = 1;
				break;
			}
```

The above is from some previous experimentation that I have done integrating the grapheme library in dwm in place of the existing implementation.

**Comment by speedie1337** [comment]
libgrapheme seems like the right library to use for this, given it's also suckless in nature. Maybe if you're a wizard you could figure out how to do this without a library, but I think this seems like a good solution. I think it's very likely the original author just assumed that since it can draw ASCII characters correctly, it should draw other characters too when that's not necessarily the case.

**Comment by bakkeby** [comment]
You can most likely also use utf8decode. It would be part of the code that the pango patch deletes, but one could undo that.

When using pango markup I'd expect the highlighting to break things, like if you have bold text then the highlighted text would not be bold for example. Probably not worth the effort of trying to fix that.

**Comment by bakkeby** [comment]
Closing this based on the above commit.
